# Generated by Django 5.0.6 on 2024-07-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="code",
            field=models.TextField(default="ntahoeunthoneuth"),
            preserve_default=False,
        ),
    ]
